const C=window.KAMBOS_CONFIG, S=C.supabaseUrl&&C.supabaseAnonKey?supabase.createClient(C.supabaseUrl,C.supabaseAnonKey):null;
const imgs={Audi:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=82',BMW:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=900&q=82','Mercedes-Benz':'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=900&q=82',Ford:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=82',Hyundai:'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=900&q=82',Kia:'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=82',MG:'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=82',Volkswagen:'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=900&q=82',Chery:'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=82','Land Rover':'https://images.unsplash.com/photo-1519245659620-e859806a8d3b?auto=format&fit=crop&w=900&q=82',Renault:'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=900&q=82','Citroën':'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=82',Peugeot:'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=900&q=82','Škoda':'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=82'};
const cars=[
['audi-a3','Audi','A3','',50,35,'','',''],['audi-a4','Audi','A4','2015',50,35,'2.0 Diesel','Automat',''],['audi-a5','Audi','A5','',55,38.5,'2.0 Diesel','Automat',''],['audi-a7','Audi','A7','',80,56,'3.0 TDI','Automat',''],
['bmw-1-1','BMW','Series 1','Njësia 1',45,31.5,'2.0 Diesel','Automat',''],['bmw-1-2','BMW','Series 1','Njësia 2',45,31.5,'2.0 Diesel','Automat',''],['bmw-3','BMW','Series 3','',55,38.5,'','',''],
['cla','Mercedes-Benz','CLA','2017',55,38.5,'2.0 Diesel','Automat',''],['c-class','Mercedes-Benz','C-Class','2016',60,42,'2.2 Diesel','Automat',''],['focus','Ford','Focus','',40,28,'2.0 Diesel','Automat',''],
['bayon','Hyundai','Bayon','2025',50,35,'1.2 Benzinë','','SUV'],['stonic-1','Kia','Stonic','Njësia 1 · 2025',50,35,'1.4 Benzinë','','SUV'],['stonic-2','Kia','Stonic','Njësia 2 · 2025',50,35,'1.4 Benzinë','','SUV'],['stonic-3','Kia','Stonic','Njësia 3 · 2025',50,35,'1.4 Benzinë','','SUV'],
['kona','Hyundai','Kona','',50,35,'1.6 Diesel','Automat','SUV'],['i30','Hyundai','i30','2015',45,31.5,'1.6 Diesel','Automat',''],['mg3','MG','MG3','',48,33.6,'1.5 Benzinë','Automat','CarPlay'],['golf-6','Volkswagen','Golf 6','',42,29.4,'1.6 Diesel','Automat',''],['golf-7','Volkswagen','Golf 7','1.6 Diesel',48,33.6,'1.6 Diesel','Automat',''],
['chery-tiggo-8','Chery','Tiggo 8','2025 · 7 vende',80,56,'Benzinë','Automat','SUV'],['chery-fx','Chery','FX','2025',60,42,'1.5 Benzinë','Automat','SUV'],['palisade','Hyundai','Palisade','2022 · 7 vende',90,63,'2.2 Diesel','Automat','SUV'],['sportage-2023','Kia','Sportage','2023',70,49,'2.0 Diesel','Automat','SUV'],['santa-fe-2020','Hyundai','Santa Fe','2020 · 7 vende',70,49,'2.2 Diesel','Automat','SUV'],['santa-fe-2015','Hyundai','Santa Fe','2015 · E bardhë',60,42,'2.2 Diesel','Automat','SUV'],['carnival','Kia','Carnival','2017 · 9 vende',75,52.5,'2.0 Diesel','',''],['evoque','Land Rover','Range Rover Evoque','E bardhë',65,45.5,'2.2 Diesel','Automat','SUV'],['evoque-grey','Land Rover','Range Rover Evoque','Gri',65,45.5,'2.2 Diesel','Automat','SUV'],['tiguan','Volkswagen','Tiguan','',55,38.5,'2.0 Diesel','Automat','SUV'],['clio','Renault','Clio','2015',38,26.6,'1.5 Diesel','Manual',''],['fiesta','Ford','Fiesta','',38,26.6,'1.5 Diesel','Manual',''],['c-elysee','Citroën','C-Elysée','2017',40,28,'1.6 Diesel','Manual',''],['golf-7-manual','Volkswagen','Golf 7 Variant','1.2 Benzinë',40,28,'1.2 Benzinë','Manual','Bagazh i madh · Tavan panoramik'],['peugeot-2019','Peugeot','208','2019',38,26.6,'1.6 Diesel','Manual','Multimedia · Bluetooth · Navigim'],['fabia-petrol','Škoda','Fabia','1.2 Benzinë',36,25.2,'1.2 Benzinë','Manual',''],['fabia-diesel','Škoda','Fabia','1.6 Diesel',36,25.2,'1.6 Diesel','',''],['sportage-2018','Kia','Sportage','2018 · E bardhë',55,38.5,'2.0 Diesel','Automat','SUV · Sunroof · Android Auto · Apple CarPlay']
].map(x=>({id:x[0],brand:x[1],model:x[2],meta:x[3],price:x[4],sale:x[5],engine:x[6],trans:x[7],tag:x[8],image:imgs[x[1]]}));
cars.find(c=>c.id==='chery-tiggo-8').image='assets/cars/chery-tiggo-8/main.png';
cars.find(c=>c.id==='chery-fx').image='assets/cars/chery-fx/main.jpeg';
cars.find(c=>c.id==='palisade').image='assets/cars/hyundai-palisade/main.jpeg';
cars.find(c=>c.id==='sportage-2023').image='assets/cars/kia-sportage-2023/main.png';
cars.find(c=>c.id==='santa-fe-2020').image='assets/cars/hyundai-santa-fe-2020/main.png';
cars.find(c=>c.id==='santa-fe-2015').image='assets/cars/hyundai-santa-fe-2015/main.png';
cars.find(c=>c.id==='carnival').image='assets/cars/kia-carnival/main.jpeg';
cars.find(c=>c.id==='evoque').image='assets/cars/range-rover-evoque/main.png';
cars.find(c=>c.id==='evoque-grey').image='assets/cars/range-rover-evoque-grey/main.png';
cars.find(c=>c.id==='tiguan').image='assets/cars/volkswagen-tiguan/main.png';
cars.find(c=>c.id==='clio').image='assets/cars/renault-clio/main.jpeg';
cars.find(c=>c.id==='fiesta').image='assets/cars/ford-fiesta/main.png';
cars.find(c=>c.id==='c-elysee').image='assets/cars/citroen-c-elysee/main.png';
cars.find(c=>c.id==='golf-7-manual').image='assets/cars/volkswagen-golf-7-variant/main.jpeg';
cars.find(c=>c.id==='peugeot-2019').image='assets/cars/peugeot-208/main.png';
cars.find(c=>c.id==='fabia-diesel').trans='Manual';
cars.find(c=>c.id==='fabia-diesel').image='assets/cars/skoda-fabia-diesel/main.jpeg';
cars.find(c=>c.id==='sportage-2018').image='assets/cars/kia-sportage-2018/main.png';
cars.find(c=>c.id==='audi-a4').image='assets/cars/audi-a4/main.png';
cars.find(c=>c.id==='audi-a5').image='assets/cars/audi-a5/main.png';
cars.find(c=>c.id==='audi-a7').image='assets/cars/audi-a7/main.png';
cars.find(c=>c.id==='bmw-1-1').image='assets/cars/bmw-series-1/main.png';
cars.find(c=>c.id==='bmw-1-2').image='assets/cars/bmw-series-1-white/main.png';
cars.find(c=>c.id==='cla').image='assets/cars/mercedes-cla/main.png';
cars.find(c=>c.id==='c-class').image='assets/cars/mercedes-c-class/main.png';
cars.find(c=>c.id==='focus').image='assets/cars/ford-focus/main.png';
cars.find(c=>c.id==='audi-a3').image='assets/cars/audi-a3/main.jpg';
cars.find(c=>c.id==='bmw-3').image='assets/cars/bmw-series-3/main.jpg';
cars.find(c=>c.id==='i30').image='assets/cars/hyundai-i30/main.jpg';
cars.find(c=>c.id==='mg3').image='assets/cars/mg3/main.jpg';
cars.find(c=>c.id==='fabia-petrol').image='assets/cars/skoda-fabia-petrol/main.jpg';
cars.find(c=>c.id==='bayon').image='assets/cars/hyundai-bayon/main.jpeg';
cars.find(c=>c.id==='stonic-1').image='assets/cars/kia-stonic/main.png';
cars.find(c=>c.id==='stonic-2').image='assets/cars/kia-stonic/main.png';
cars.find(c=>c.id==='stonic-3').image='assets/cars/kia-stonic/main.png';
cars.find(c=>c.id==='kona').image='assets/cars/hyundai-kona/main.jpeg';
cars.find(c=>c.id==='golf-6').image='assets/cars/volkswagen-golf-6/main.png';
cars.find(c=>c.id==='golf-7').image='assets/cars/volkswagen-golf-7/main.jpeg';

const carGalleries={
  'audi-a5':['assets/cars/audi-a5/main.png','assets/cars/audi-a5/02.png','assets/cars/audi-a5/03.png'],
  'audi-a7':['assets/cars/audi-a7/main.png','assets/cars/audi-a7/02.png'],
  'bmw-1-1':['assets/cars/bmw-series-1/main.png','assets/cars/bmw-series-1/02.png'],
  'bmw-1-2':['assets/cars/bmw-series-1-white/main.png','assets/cars/bmw-series-1-white/02.png','assets/cars/bmw-series-1-white/03.png'],
  'cla':['assets/cars/mercedes-cla/main.png','assets/cars/mercedes-cla/02.png','assets/cars/mercedes-cla/03.png','assets/cars/mercedes-cla/04.png'],
  'c-class':['assets/cars/mercedes-c-class/main.png','assets/cars/mercedes-c-class/02.png'],
  'focus':['assets/cars/ford-focus/main.png','assets/cars/ford-focus/02.png','assets/cars/ford-focus/03.png','assets/cars/ford-focus/04.png']
};
Object.assign(carGalleries,{
  'audi-a3':['assets/cars/audi-a3/main.jpg','assets/cars/audi-a3/rear.jpg','assets/cars/audi-a3/front.jpg','assets/cars/audi-a3/interior.jpg'],
  'audi-a4':['assets/cars/audi-a4/main.png','assets/cars/audi-a4/angle.png','assets/cars/audi-a4/rear.png','assets/cars/audi-a4/interior.png'],
  'bmw-3':['assets/cars/bmw-series-3/main.jpg','assets/cars/bmw-series-3/rear.jpg','assets/cars/bmw-series-3/rear-seats.jpg','assets/cars/bmw-series-3/front-cabin.jpg'],
  'i30':['assets/cars/hyundai-i30/main.jpg','assets/cars/hyundai-i30/rear.jpg','assets/cars/hyundai-i30/front.jpg','assets/cars/hyundai-i30/rear-straight.jpg','assets/cars/hyundai-i30/panoramic-roof.jpg','assets/cars/hyundai-i30/interior.jpg'],
  'mg3':['assets/cars/mg3/main.jpg','assets/cars/mg3/rear.jpg','assets/cars/mg3/carplay.jpg','assets/cars/mg3/front-seats.jpg','assets/cars/mg3/luggage.jpg','assets/cars/mg3/interior.jpg'],
  'chery-tiggo-8':['assets/cars/chery-tiggo-8/main.png','assets/cars/chery-tiggo-8/rear.png','assets/cars/chery-tiggo-8/front.jpeg','assets/cars/chery-tiggo-8/interior-camera.jpeg','assets/cars/chery-tiggo-8/interior-cockpit.jpeg','assets/cars/chery-tiggo-8/interior-driving.jpeg','assets/cars/chery-tiggo-8/interior-roof.jpeg','assets/cars/chery-tiggo-8/interior-wide.jpeg'],
  'chery-fx':['assets/cars/chery-fx/main.jpeg','assets/cars/chery-fx/interior-front.jpeg','assets/cars/chery-fx/interior-rear.jpeg','assets/cars/chery-fx/interior-wide.jpeg'],
  'palisade':['assets/cars/hyundai-palisade/main.jpeg','assets/cars/hyundai-palisade/rear.png','assets/cars/hyundai-palisade/front.jpeg','assets/cars/hyundai-palisade/grille.jpeg','assets/cars/hyundai-palisade/interior.jpeg','assets/cars/hyundai-palisade/digital-cluster.jpeg','assets/cars/hyundai-palisade/taillight.jpeg'],
  'sportage-2023':['assets/cars/kia-sportage-2023/main.png','assets/cars/kia-sportage-2023/rear.png','assets/cars/kia-sportage-2023/side.jpeg','assets/cars/kia-sportage-2023/dashboard.jpeg','assets/cars/kia-sportage-2023/driver-view.jpeg','assets/cars/kia-sportage-2023/interior-front.jpeg','assets/cars/kia-sportage-2023/interior-wide.jpeg','assets/cars/kia-sportage-2023/rear-seats.jpeg'],
  'santa-fe-2020':['assets/cars/hyundai-santa-fe-2020/main.png','assets/cars/hyundai-santa-fe-2020/rear.png','assets/cars/hyundai-santa-fe-2020/side.jpeg','assets/cars/hyundai-santa-fe-2020/interior.jpeg'],
  'santa-fe-2015':['assets/cars/hyundai-santa-fe-2015/main.png','assets/cars/hyundai-santa-fe-2015/rear.png','assets/cars/hyundai-santa-fe-2015/dashboard-panorama.jpeg','assets/cars/hyundai-santa-fe-2015/rear-cabin.jpeg','assets/cars/hyundai-santa-fe-2015/rear-seats.jpeg','assets/cars/hyundai-santa-fe-2015/third-row.jpeg'],
  'carnival':['assets/cars/kia-carnival/main.jpeg','assets/cars/kia-carnival/front.png','assets/cars/kia-carnival/rear.png','assets/cars/kia-carnival/driver-cabin.jpeg','assets/cars/kia-carnival/passenger-seating.jpeg','assets/cars/kia-carnival/sliding-door-cabin.jpeg'],
  'evoque':['assets/cars/range-rover-evoque/main.png','assets/cars/range-rover-evoque/rear.png','assets/cars/range-rover-evoque/side.jpeg','assets/cars/range-rover-evoque/automatic-console.jpeg','assets/cars/range-rover-evoque/front-seats.jpeg','assets/cars/range-rover-evoque/meridian-audio.jpeg','assets/cars/range-rover-evoque/panoramic-cabin.jpeg','assets/cars/range-rover-evoque/rear-seats.jpeg'],
  'evoque-grey':['assets/cars/range-rover-evoque-grey/main.png','assets/cars/range-rover-evoque-grey/rear.png','assets/cars/range-rover-evoque-grey/front-cabin.jpeg','assets/cars/range-rover-evoque-grey/rear-seats-panorama.jpeg'],
  'tiguan':['assets/cars/volkswagen-tiguan/main.png','assets/cars/volkswagen-tiguan/rear-luggage.png','assets/cars/volkswagen-tiguan/front-cabin.jpeg','assets/cars/volkswagen-tiguan/rear-seats-panorama.jpeg'],
  'clio':['assets/cars/renault-clio/main.jpeg','assets/cars/renault-clio/front.png','assets/cars/renault-clio/rear.png','assets/cars/renault-clio/manual-dashboard.jpeg'],
  'fiesta':['assets/cars/ford-fiesta/main.png','assets/cars/ford-fiesta/rear.png','assets/cars/ford-fiesta/manual-dashboard.jpeg'],
  'c-elysee':['assets/cars/citroen-c-elysee/main.png','assets/cars/citroen-c-elysee/front.png'],
  'golf-7-manual':['assets/cars/volkswagen-golf-7-variant/main.jpeg','assets/cars/volkswagen-golf-7-variant/rear.jpeg','assets/cars/volkswagen-golf-7-variant/dashboard.jpeg','assets/cars/volkswagen-golf-7-variant/interior.jpeg'],
  'peugeot-2019':['assets/cars/peugeot-208/main.png','assets/cars/peugeot-208/side.png','assets/cars/peugeot-208/interior.jpeg'],
  'fabia-petrol':['assets/cars/skoda-fabia-petrol/main.jpg','assets/cars/skoda-fabia-petrol/rear.jpg'],
  'fabia-diesel':['assets/cars/skoda-fabia-diesel/main.jpeg','assets/cars/skoda-fabia-diesel/rear.jpeg','assets/cars/skoda-fabia-diesel/dashboard.jpeg','assets/cars/skoda-fabia-diesel/interior.jpeg'],
  'sportage-2018':['assets/cars/kia-sportage-2018/main.png','assets/cars/kia-sportage-2018/rear.png']
  ,'bayon':['assets/cars/hyundai-bayon/main.jpeg','assets/cars/hyundai-bayon/rear.jpeg','assets/cars/hyundai-bayon/front.jpeg','assets/cars/hyundai-bayon/front-cabin.jpeg','assets/cars/hyundai-bayon/rear-seats.jpeg']
  ,'stonic-1':['assets/cars/kia-stonic/main.png','assets/cars/kia-stonic/side.jpeg','assets/cars/kia-stonic/interior.jpeg']
  ,'stonic-2':['assets/cars/kia-stonic/main.png','assets/cars/kia-stonic/side.jpeg','assets/cars/kia-stonic/interior.jpeg']
  ,'stonic-3':['assets/cars/kia-stonic/main.png','assets/cars/kia-stonic/side.jpeg','assets/cars/kia-stonic/interior.jpeg']
  ,'kona':['assets/cars/hyundai-kona/main.jpeg','assets/cars/hyundai-kona/rear-side.jpeg','assets/cars/hyundai-kona/luggage.jpeg','assets/cars/hyundai-kona/interior.jpeg']
  ,'golf-6':['assets/cars/volkswagen-golf-6/main.png','assets/cars/volkswagen-golf-6/front.png','assets/cars/volkswagen-golf-6/interior.jpeg']
  ,'golf-7':['assets/cars/volkswagen-golf-7/main.jpeg','assets/cars/volkswagen-golf-7/front.jpeg','assets/cars/volkswagen-golf-7/rear.jpeg','assets/cars/volkswagen-golf-7/interior.jpeg']
});
let blocked={}; const money=n=>`€${Number.isInteger(n)?n:n.toFixed(2)}`; const iso=d=>d.toISOString().slice(0,10); const today=iso(new Date());
document.querySelectorAll('input[type=date]').forEach(i=>{i.min=today;i.max=C.seasonEnd});
async function loadBlocked(){if(S){const {data}=await S.from('blocked_dates').select('*');(data||[]).forEach(b=>(blocked[b.vehicle_id]??=[]).push([b.start_date,b.end_date]));}else blocked=JSON.parse(localStorage.getItem('kambos_blocked')||'{}');render();}
const unavailable=(id,start,end)=>{if(!start||!end)return false;const s=new Date(start+'T12:00'),e=new Date(end+'T12:00');return (blocked[id]||[]).some(([a,b])=>s<=new Date(b+'T12:00')&&e>=new Date(a+'T12:00'));};
function render(filter='all'){const s=globalStart.value,e=globalEnd.value;let list=cars.filter(c=>filter==='all'||c.brand===filter||c.tag===filter);if(s&&e)list=list.filter(c=>!unavailable(c.id,s,e));fleetStatus.textContent=`${list.length} makina të disponueshme${s&&e?' për datat e zgjedhura':''}.`;fleetGrid.innerHTML=list.map(c=>`<article class="car-card"><button class="car-open" data-id="${c.id}"><div class="car-image"><img src="${c.image}" alt="${c.brand} ${c.model}" loading="lazy"></div><div class="car-body"><small>${c.meta||c.brand}</small><h3>${c.brand} ${c.model}</h3><div class="specs"><span>${c.trans||c.engine||'4 dyer'}</span><span>${c.engine&&c.trans?c.engine:'4 dyer'}</span></div></div></button></article>`).join('');document.querySelectorAll('.car-open').forEach(b=>b.onclick=()=>openCar(b.dataset.id));}
function priceFor(start,end,car){const a=new Date(start+'T12:00'),b=new Date(end+'T12:00');let days=Math.max(1,Math.round((b-a)/864e5)),normal=0,sale=0,winter=0,total=0;for(let i=0;i<days;i++){const d=new Date(a);d.setDate(d.getDate()+i);if(d>=new Date('2027-06-01T12:00')){sale++;total+=car.price*.9}else if(d>=new Date('2027-04-01T12:00')){sale++;total+=car.price*.7}else if(d>=new Date('2027-03-31T12:00')){normal++;total+=car.price}else if(d>=new Date('2027-01-16T12:00')){sale++;total+=car.price*.65}else if(d>=new Date('2026-12-15T12:00')){winter++;total+=car.sale*1.2}else if(d>=new Date('2026-09-15T12:00')){sale++;total+=car.sale}else{normal++;total+=car.price}}return{days,normal,sale,winter,total};}
function openCar(id){const c=cars.find(x=>x.id===id),s=globalStart.value,e=globalEnd.value,gallery=carGalleries[id]||[c.image];modalContent.innerHTML=`<div class="modal-hero"><div class="modal-gallery"><img class="modal-main-image" src="${gallery[0]}" alt="${c.brand} ${c.model}">${gallery.length>1?`<div class="modal-thumbs">${gallery.map((src,index)=>`<button class="modal-thumb${index===0?' active':''}" type="button" data-src="${src}" aria-label="Foto ${index+1}"><img src="${src}" alt=""></button>`).join('')}</div>`:''}</div><div><span>${c.meta}</span><h2>${c.brand} ${c.model}</h2><p>${[c.engine,c.trans,c.tag,'4 dyer'].filter(Boolean).join(' · ')}</p></div></div><form id="reserveForm"><div class="form-grid"><label>Emri i plotë<input name="name" required></label><label>Telefoni<input name="phone" type="tel" required></label><label>Ora e marrjes<input name="startTime" type="time" required></label><label>Ora e kthimit<input name="endTime" type="time" required></label></div><input name="start" type="hidden" value="${s}"><input name="end" type="hidden" value="${e}"><div class="calendar-wrap"><div class="calendar-head"><button type="button" class="cal-nav" id="calPrev">‹</button><div><b id="monthLabel"></b><small id="selectionLabel">Zgjidh datën e marrjes dhe kthimit</small></div><button type="button" class="cal-nav" id="calNext">›</button></div><div class="calendar-legend"><span><i class="legend-available"></i>E lirë</span><span><i class="legend-blocked"></i>E rezervuar</span><span><i class="legend-selected"></i>E zgjedhur</span></div><div class="calendar-grid" id="calendarGrid"></div></div><label class="check"><input name="seat" type="checkbox"> Karrige për fëmijë <b>+€4</b></label><label>Shënim (opsional)<textarea name="note" rows="3"></textarea></label><div class="availability" id="availability">Zgjidh datat për të parë çmimin.</div><button class="btn full" type="submit">Dërgo kërkesën në WhatsApp</button><small>Kërkesa konfirmohet vetëm pasi KamboS t’ju përgjigjet.</small></form>`;bookingModal.classList.add('show');bookingModal.ariaHidden='false';modalContent.querySelectorAll('.modal-thumb').forEach(btn=>btn.onclick=()=>{modalContent.querySelector('.modal-main-image').src=btn.dataset.src;modalContent.querySelectorAll('.modal-thumb').forEach(x=>x.classList.remove('active'));btn.classList.add('active')});const f=document.querySelector('#reserveForm');f.oninput=()=>quote(f,c);f.onsubmit=x=>send(x,f,c);initCalendar(f,c);quote(f,c);}
function initCalendar(f,c){const months=['Janar','Shkurt','Mars','Prill','Maj','Qershor','Korrik','Gusht','Shtator','Tetor','Nëntor','Dhjetor'],days=['Hë','Ma','Më','En','Pr','Sh','Di'];let view=f.start.value?new Date(f.start.value+'T12:00'):new Date();view=new Date(view.getFullYear(),view.getMonth(),1,12);const min=new Date(today+'T12:00'),max=new Date(C.seasonEnd+'T12:00');function rangeHasBlock(a,b){for(let d=new Date(a);d<=b;d.setDate(d.getDate()+1))if(unavailable(c.id,iso(d),iso(d)))return true;return false}function draw(){monthLabel.textContent=`${months[view.getMonth()]} ${view.getFullYear()}`;const first=(new Date(view.getFullYear(),view.getMonth(),1).getDay()+6)%7,last=new Date(view.getFullYear(),view.getMonth()+1,0).getDate();let html=days.map(d=>`<span class="cal-dayname">${d}</span>`).join('')+Array(first).fill('<span></span>').join('');for(let n=1;n<=last;n++){const d=new Date(view.getFullYear(),view.getMonth(),n,12),key=iso(d),isBlocked=unavailable(c.id,key,key),disabled=d<min||d>max||isBlocked,selected=key===f.start.value||key===f.end.value,inRange=f.start.value&&f.end.value&&key>f.start.value&&key<f.end.value;html+=`<button type="button" class="cal-day${isBlocked?' blocked':''}${selected?' selected':''}${inRange?' in-range':''}" data-date="${key}" ${disabled?'disabled':''}>${n}</button>`}calendarGrid.innerHTML=html;selectionLabel.textContent=f.start.value?(f.end.value?`${f.start.value} → ${f.end.value}`:`Marrja: ${f.start.value} · zgjidh kthimin`):'Zgjidh datën e marrjes dhe kthimit';calendarGrid.querySelectorAll('.cal-day:not(:disabled)').forEach(b=>b.onclick=()=>pick(b.dataset.date));calPrev.disabled=new Date(view.getFullYear(),view.getMonth()+1,0)<min;calNext.disabled=new Date(view.getFullYear(),view.getMonth()+1,1)>max}function pick(key){if(!f.start.value||f.end.value){f.start.value=key;f.end.value=''}else if(key<f.start.value){f.start.value=key;f.end.value=''}else{const a=new Date(f.start.value+'T12:00'),b=new Date(key+'T12:00');if(rangeHasBlock(a,b)){availability.className='availability bad';availability.textContent='Intervali përmban data të rezervuara. Zgjidh një interval tjetër.';return}f.end.value=key}draw();quote(f,c)}calPrev.onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()-1,1,12);draw()};calNext.onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1,12);draw()};draw()}
function quote(f,c){const s=f.start.value,e=f.end.value,box=document.querySelector('#availability');if(!s||!e)return;if(e<s){box.className='availability bad';box.textContent='Data e kthimit nuk mund të jetë para datës së marrjes.';return}if(unavailable(c.id,s,e)){box.className='availability bad';box.textContent='Këto data janë të bllokuara për këtë makinë.';return}const p=priceFor(s,e,c),seat=f.seat.checked?4:0;box.className='availability';box.innerHTML=`<span>${p.days} ditë</span><span>Makina: ${money(p.total)}</span>${seat?'<span>Karrige: €4</span>':''}<b>Totali: ${money(p.total+seat)}</b>`;}
function send(ev,f,c){ev.preventDefault();if(unavailable(c.id,f.start.value,f.end.value))return quote(f,c);const p=priceFor(f.start.value,f.end.value,c),seat=f.seat.checked?4:0;const msg=`Përshëndetje KamboS Rental Car!\n\nDëshiroj të kërkoj një rezervim.\n\nMakina: ${c.brand} ${c.model} ${c.meta}\nEmri: ${f.name.value}\nTelefoni: ${f.phone.value}\nData e marrjes: ${f.start.value}\nOra e marrjes: ${f.startTime.value}\nData e kthimit: ${f.end.value}\nOra e kthimit: ${f.endTime.value}\nNumri i ditëve: ${p.days}\nÇmimi për makinën: ${money(p.total)}\nKarrige për fëmijë: ${f.seat.checked?'Po, +€4':'Jo'}\nTotali: ${money(p.total+seat)}\nShënim: ${f.note.value||'-'}\n\nJu lutem më konfirmoni disponueshmërinë. Faleminderit!`;window.open(`https://wa.me/${C.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank');}
const reviews=[['Ardit K.','Makina ishte e pastër, komode dhe gati në kohë. Rezervimi ishte shumë i thjeshtë.'],['Elona M.','Komunikim i shpejtë dhe shërbim shumë korrekt. Patjetër do të rezervoj përsëri.'],['Besnik H.','Çmimi ishte transparent dhe makina ishte në gjendje shumë të mirë.'],['Sara D.','Rezervimi në WhatsApp ishte i lehtë dhe përgjigjja erdhi shumë shpejt.'],['Erion L.','Shërbim profesional, staf i sjellshëm dhe makinë shumë e pastër.']];reviewTrack.innerHTML=[...reviews,...reviews].map(r=>`<article><div class="stars">★★★★★</div><p>“${r[1]}”</p><b>${r[0]}</b></article>`).join('');
findCars.onclick=()=>render(document.querySelector('.filter.active').dataset.filter);document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)});document.querySelector('.close').onclick=()=>bookingModal.classList.remove('show');bookingModal.onclick=e=>{if(e.target===bookingModal)bookingModal.classList.remove('show')};document.querySelector('.menu').onclick=()=>document.querySelector('nav').classList.toggle('open');render();loadBlocked();
