const C=window.KAMBOS_CONFIG, S=C.supabaseUrl&&C.supabaseAnonKey?supabase.createClient(C.supabaseUrl,C.supabaseAnonKey):null;
const imgs={Audi:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=82',BMW:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=900&q=82','Mercedes-Benz':'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=900&q=82',Ford:'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=82',Hyundai:'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=900&q=82',Kia:'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=82',MG:'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=900&q=82',Volkswagen:'https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=900&q=82'};
const cars=[
['audi-a3','Audi','A3','',50,35,'','',''],['audi-a4','Audi','A4','2015',50,35,'2.0 Diesel','Automat',''],['audi-a5','Audi','A5','',55,38.5,'2.0 Diesel','Automat',''],['audi-a7','Audi','A7','',80,56,'3.0 TDI','Automat',''],
['bmw-1-1','BMW','Series 1','Njësia 1',45,31.5,'2.0 Diesel','Automat',''],['bmw-1-2','BMW','Series 1','Njësia 2',45,31.5,'2.0 Diesel','Automat',''],['bmw-3','BMW','Series 3','',55,38.5,'','',''],
['cla','Mercedes-Benz','CLA','2017',55,38.5,'2.0 Diesel','Automat',''],['c-class','Mercedes-Benz','C-Class','2016',60,42,'2.2 Diesel','Automat',''],['focus','Ford','Focus','',40,28,'2.0 Diesel','Automat',''],
['bayon','Hyundai','Bayon','2025',50,35,'1.2 Benzinë','','SUV'],['stonic-1','Kia','Stonic','Njësia 1 · 2025',50,35,'1.4 Benzinë','','SUV'],['stonic-2','Kia','Stonic','Njësia 2 · 2025',50,35,'1.4 Benzinë','','SUV'],['stonic-3','Kia','Stonic','Njësia 3 · 2025',50,35,'1.4 Benzinë','','SUV'],
['kona','Hyundai','Kona','',50,35,'1.6 Diesel','Automat','SUV'],['i30','Hyundai','i30','2015',45,31.5,'1.6 Diesel','Automat',''],['mg3','MG','MG3','',48,33.6,'1.5 Benzinë','Automat','CarPlay'],['golf-6','Volkswagen','Golf 6','',42,29.4,'1.6 Diesel','Automat',''],['golf-7','Volkswagen','Golf 7','',48,33.6,'1.6 Diesel','Automat','']
].map(x=>({id:x[0],brand:x[1],model:x[2],meta:x[3],price:x[4],sale:x[5],engine:x[6],trans:x[7],tag:x[8],image:imgs[x[1]]}));
let blocked={}; const money=n=>`€${Number.isInteger(n)?n:n.toFixed(2)}`; const iso=d=>d.toISOString().slice(0,10); const today=iso(new Date());
document.querySelectorAll('input[type=date]').forEach(i=>{i.min=today;i.max=C.seasonEnd});
async function loadBlocked(){if(S){const {data}=await S.from('blocked_dates').select('*');(data||[]).forEach(b=>(blocked[b.vehicle_id]??=[]).push([b.start_date,b.end_date]));}else blocked=JSON.parse(localStorage.getItem('kambos_blocked')||'{}');render();}
const unavailable=(id,start,end)=>{if(!start||!end)return false;const s=new Date(start+'T12:00'),e=new Date(end+'T12:00');return (blocked[id]||[]).some(([a,b])=>s<=new Date(b+'T12:00')&&e>=new Date(a+'T12:00'));};
function render(filter='all'){const s=globalStart.value,e=globalEnd.value;let list=cars.filter(c=>filter==='all'||c.brand===filter||c.tag===filter);if(s&&e)list=list.filter(c=>!unavailable(c.id,s,e));fleetStatus.textContent=`${list.length} makina të disponueshme${s&&e?' për datat e zgjedhura':''}.`;fleetGrid.innerHTML=list.map(c=>`<article class="car-card"><button class="car-open" data-id="${c.id}"><div class="car-image"><img src="${c.image}" alt="${c.brand} ${c.model}" loading="lazy"><span class="sale">−30%</span></div><div class="car-body"><small>${c.meta||c.brand}</small><h3>${c.brand} ${c.model}</h3><div class="specs"><span>${c.trans||c.engine||'4 dyer'}</span><span>${c.engine&&c.trans?c.engine:'4 dyer'}</span></div><div class="price"><b>${money(c.price)}</b><span>/ ditë</span></div></div></button></article>`).join('');document.querySelectorAll('.car-open').forEach(b=>b.onclick=()=>openCar(b.dataset.id));}
function priceFor(start,end,car){const a=new Date(start+'T12:00'),b=new Date(end+'T12:00');let days=Math.max(1,Math.round((b-a)/864e5)),normal=0,sale=0,total=0;for(let i=0;i<days;i++){const d=new Date(a);d.setDate(d.getDate()+i);if(d>=new Date('2026-09-15T12:00')){sale++;total+=car.sale}else{normal++;total+=car.price}}return{days,normal,sale,total};}
function openCar(id){const c=cars.find(x=>x.id===id),s=globalStart.value,e=globalEnd.value;modalContent.innerHTML=`<div class="modal-hero"><img src="${c.image}" alt="${c.brand} ${c.model}"><div><span>${c.meta}</span><h2>${c.brand} ${c.model}</h2><p>${[c.engine,c.trans,c.tag,'4 dyer'].filter(Boolean).join(' · ')}</p></div></div><form id="reserveForm"><div class="form-grid"><label>Emri i plotë<input name="name" required></label><label>Telefoni<input name="phone" type="tel" required></label><label>Data e marrjes<input name="start" type="date" min="${today}" max="${C.seasonEnd}" value="${s}" required></label><label>Data e kthimit<input name="end" type="date" min="${today}" max="${C.seasonEnd}" value="${e}" required></label><label>Ora e marrjes<input name="startTime" type="time" required></label><label>Ora e kthimit<input name="endTime" type="time" required></label></div><label class="check"><input name="seat" type="checkbox"> Karrige për fëmijë <b>+€4</b></label><label>Shënim (opsional)<textarea name="note" rows="3"></textarea></label><div class="availability" id="availability">Zgjidh datat për të parë çmimin.</div><button class="btn full" type="submit">Dërgo kërkesën në WhatsApp</button><small>Kërkesa konfirmohet vetëm pasi KamboS t’ju përgjigjet.</small></form>`;bookingModal.classList.add('show');bookingModal.ariaHidden='false';const f=document.querySelector('#reserveForm');f.oninput=()=>quote(f,c);f.onsubmit=x=>send(x,f,c);quote(f,c);}
function quote(f,c){const s=f.start.value,e=f.end.value,box=document.querySelector('#availability');if(!s||!e)return;if(e<s){box.className='availability bad';box.textContent='Data e kthimit nuk mund të jetë para datës së marrjes.';return}if(unavailable(c.id,s,e)){box.className='availability bad';box.textContent='Këto data janë të bllokuara për këtë makinë.';return}const p=priceFor(s,e,c),seat=f.seat.checked?4:0;box.className='availability';box.innerHTML=`<span>${p.days} ditë</span><span>Makina: ${money(p.total)}</span>${seat?'<span>Karrige: €4</span>':''}<b>Totali: ${money(p.total+seat)}</b>`;}
function send(ev,f,c){ev.preventDefault();if(unavailable(c.id,f.start.value,f.end.value))return quote(f,c);const p=priceFor(f.start.value,f.end.value,c),seat=f.seat.checked?4:0;const msg=`Përshëndetje KamboS Rental Car!\n\nDëshiroj të kërkoj një rezervim.\n\nMakina: ${c.brand} ${c.model} ${c.meta}\nEmri: ${f.name.value}\nTelefoni: ${f.phone.value}\nData e marrjes: ${f.start.value}\nOra e marrjes: ${f.startTime.value}\nData e kthimit: ${f.end.value}\nOra e kthimit: ${f.endTime.value}\nNumri i ditëve: ${p.days}\nÇmimi për makinën: ${money(p.total)}\nKarrige për fëmijë: ${f.seat.checked?'Po, +€4':'Jo'}\nTotali: ${money(p.total+seat)}\nShënim: ${f.note.value||'-'}\n\nJu lutem më konfirmoni disponueshmërinë. Faleminderit!`;window.open(`https://wa.me/${C.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank');}
const reviews=[['Ardit K.','Makina ishte e pastër, komode dhe gati në kohë. Rezervimi ishte shumë i thjeshtë.'],['Elona M.','Komunikim i shpejtë dhe shërbim shumë korrekt. Patjetër do të rezervoj përsëri.'],['Besnik H.','Çmimi ishte transparent dhe makina ishte në gjendje shumë të mirë.'],['Sara D.','Rezervimi në WhatsApp ishte i lehtë dhe përgjigjja erdhi shumë shpejt.'],['Erion L.','Shërbim profesional, staf i sjellshëm dhe makinë shumë e pastër.']];reviewTrack.innerHTML=[...reviews,...reviews].map(r=>`<article><div class="stars">★★★★★</div><p>“${r[1]}”</p><b>${r[0]}</b></article>`).join('');
findCars.onclick=()=>render(document.querySelector('.filter.active').dataset.filter);document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)});document.querySelector('.close').onclick=()=>bookingModal.classList.remove('show');bookingModal.onclick=e=>{if(e.target===bookingModal)bookingModal.classList.remove('show')};document.querySelector('.menu').onclick=()=>document.querySelector('nav').classList.toggle('open');render();loadBlocked();
