const C=window.KAMBOS_CONFIG, S=C.supabaseUrl&&C.supabaseAnonKey?supabase.createClient(C.supabaseUrl,C.supabaseAnonKey):null;
let currentLang=localStorage.getItem('kambos_lang_v13')||'en';
const ui={sq:{available:'makina të disponueshme',chosen:'për datat e zgjedhura',perDay:'/ ditë',doors:'4 dyer',photo:'Foto',fullName:'Emri i plotë',phone:'Telefoni',pickupTime:'Ora e marrjes',returnTime:'Ora e kthimit',selectDates:'Zgjidh datën e marrjes dhe kthimit',availableDay:'E lirë',reserved:'E rezervuar',selected:'E zgjedhur',pickup:'Marrja',chooseReturn:'zgjidh kthimin',childSeat:'Karrige për fëmijë',insurance:'Siguracion e plotë',crossBorder:'Cross border',addDriver:'Shofer shtesë',note:'Shënim (opsional)',seePrice:'Zgjidh datat për të parë çmimin.',send:'Dërgo kërkesën në WhatsApp',confirmation:'Kërkesa konfirmohet vetëm pasi KamboS t’ju përgjigjet.',days:'ditë',car:'Makina',total:'Totali',badOrder:'Data e kthimit nuk mund të jetë para datës së marrjes.',blocked:'Këto data janë të bllokuara për këtë makinë.',blockedRange:'Intervali përmban data të rezervuara. Zgjidh një interval tjetër.'},en:{available:'cars available',chosen:'for the selected dates',perDay:'/ day',doors:'4 doors',photo:'Photo',fullName:'Full name',phone:'Phone',pickupTime:'Pick-up time',returnTime:'Return time',selectDates:'Select pick-up and return dates',availableDay:'Available',reserved:'Reserved',selected:'Selected',pickup:'Pick-up',chooseReturn:'choose return date',childSeat:'Child seat',insurance:'Full insurance',crossBorder:'Cross border',addDriver:'Additional driver',note:'Note (optional)',seePrice:'Select dates to see the price.',send:'Send request on WhatsApp',confirmation:'The request is confirmed only after KamboS replies.',days:'days',car:'Car',total:'Total',badOrder:'The return date cannot be before the pick-up date.',blocked:'These dates are unavailable for this car.',blockedRange:'This range contains reserved dates. Please select another range.'}};
const T=()=>ui[currentLang];
const staticCopy={
  en:{navFleet:'Cars',navHow:'How it works',navReviews:'Reviews',navContact:'Contact',bookNow:'Book now',heroEyebrow:'TIRANA AIRPORT · ALL OF ALBANIA',heroTitle:'The right car for every journey.',heroText:'Choose your car, check available dates and send your request directly on WhatsApp.',viewCars:'View cars',trustOne:'✓ Price shown after selecting dates',trustTwo:'✓ Simple booking',trustThree:'✓ Fast response',pickupDate:'Pick-up date',returnDate:'Return date',findCars:'Find cars',fleetEyebrow:'OUR FLEET',fleetTitle:'Choose your car',allCars:'All',simpleFast:'SIMPLE AND FAST',howTitle:'How it works',step1Title:'Choose a car',step1Text:'Browse the fleet and confirmed specifications.',step2Title:'Choose dates',step2Text:'Unavailable dates are light red and cannot be selected.',step3Title:'Review your price',step3Text:'The full price appears only after you select the dates.',step4Title:'Send on WhatsApp',step4Text:'KamboS replies to confirm your reservation.',reviewsEyebrow:'CUSTOMER REVIEWS',reviewsTitle:'What our customers say',contactTitle:'Start your journey from Tirana Airport.',contactText:'Car rental service for travel throughout Albania.',footerPlace:'Tirana International Airport · Albania'},
  sq:{navFleet:'Makinat',navHow:'Si funksionon',navReviews:'Vlerësimet',navContact:'Kontakti',bookNow:'Rezervo',heroEyebrow:'AEROPORTI I TIRANËS · E GJITHË SHQIPËRIA',heroTitle:'Makina e duhur për çdo udhëtim.',heroText:'Zgjidh makinën, kontrollo datat e lira dhe dërgo kërkesën direkt në WhatsApp.',viewCars:'Shiko makinat',trustOne:'✓ Çmimi shfaqet pasi zgjidhni datat',trustTwo:'✓ Rezervim i thjeshtë',trustThree:'✓ Përgjigje e shpejtë',pickupDate:'Data e marrjes',returnDate:'Data e kthimit',findCars:'Gjej makina',fleetEyebrow:'FLOTA JONË',fleetTitle:'Zgjidh makinën tënde',allCars:'Të gjitha',simpleFast:'E THJESHTË DHE E SHPEJTË',howTitle:'Si funksionon',step1Title:'Zgjidh makinën',step1Text:'Shiko flotën dhe specifikat e konfirmuara.',step2Title:'Zgjidh datat',step2Text:'Datat e bllokuara janë të kuqe të hapur dhe nuk mund të zgjidhen.',step3Title:'Shiko çmimin',step3Text:'Çmimi i plotë shfaqet vetëm pasi zgjidhni datat.',step4Title:'Dërgo në WhatsApp',step4Text:'KamboS ju përgjigjet për konfirmimin.',reviewsEyebrow:'VLERËSIMET E KLIENTËVE',reviewsTitle:'Fjalë nga klientët',contactTitle:'Nis udhëtimin nga Aeroporti i Tiranës.',contactText:'Shërbim makinash me qira për udhëtime në të gjithë Shqipërinë.',footerPlace:'Aeroporti Ndërkombëtar i Tiranës · Shqipëri'}
};
function translateStatic(){document.documentElement.lang=currentLang;document.title=currentLang==='en'?'KamboS Rental Car | Tirana Airport Car Rental':'KamboS Rental Car | Makina me qira në Aeroportin e Tiranës';document.querySelectorAll('[data-i18n]').forEach(el=>{const value=staticCopy[currentLang][el.dataset.i18n];if(value)el.textContent=value});const b=document.querySelector('.lang');b.textContent=currentLang==='en'?'SQ':'EN';b.setAttribute('aria-label',currentLang==='en'?'Kalo në shqip':'Switch to English');}
const placeholder='assets/car-photo-coming-soon.svg';
const imgs={Audi:placeholder,BMW:placeholder,'Mercedes-Benz':placeholder,Ford:placeholder,Hyundai:placeholder,Kia:placeholder,MG:placeholder,Volkswagen:placeholder,Chery:placeholder,'Land Rover':placeholder,Renault:placeholder,'Citroën':placeholder,Peugeot:placeholder,'Škoda':placeholder};
const cars=[
['audi-a3','Audi','A3','',50,35,'','',''],['audi-a4','Audi','A4','2015',50,35,'2.0 Diesel','Automat',''],['audi-a5','Audi','A5','',55,38.5,'2.0 Diesel','Automat',''],['audi-a7','Audi','A7','',80,56,'3.0 TDI','Automat',''],
['bmw-1-1','BMW','Series 1','Njësia 1',45,31.5,'2.0 Diesel','Automat',''],['bmw-1-2','BMW','Series 1','Njësia 2',45,31.5,'2.0 Diesel','Automat',''],['bmw-3','BMW','Series 3','',55,38.5,'','',''],
['cla','Mercedes-Benz','CLA','2017',55,38.5,'2.0 Diesel','Automat',''],['c-class','Mercedes-Benz','C-Class','2016',60,42,'2.2 Diesel','Automat',''],['focus','Ford','Focus','',40,28,'2.0 Diesel','Automat',''],
['bayon','Hyundai','Bayon','2025',50,35,'1.2 Benzinë','','SUV'],['stonic-1','Kia','Stonic','Njësia 1 · 2025',50,35,'1.4 Benzinë','','SUV'],['stonic-2','Kia','Stonic','Njësia 2 · 2025',50,35,'1.4 Benzinë','','SUV'],['stonic-3','Kia','Stonic','Njësia 3 · 2025',50,35,'1.4 Benzinë','','SUV'],
['kona','Hyundai','Kona','',50,35,'1.6 Diesel','Automat','SUV'],['i30','Hyundai','i30','2015',45,31.5,'1.6 Diesel','Automat',''],['mg3','MG','MG3','',48,33.6,'1.5 Benzinë','Automat','CarPlay'],['golf-6','Volkswagen','Golf 6','',42,29.4,'1.6 Diesel','Automat',''],['golf-7','Volkswagen','Golf 7','1.6 Diesel',48,33.6,'1.6 Diesel','Automat',''],
['chery-tiggo-8','Chery','Tiggo 8','2025 · 7 vende',80,56,'Benzinë','Automat','SUV'],['chery-fx','Chery','FX','2025',60,42,'1.5 Benzinë','Automat','SUV'],['palisade','Hyundai','Palisade','2022 · 7 vende',90,63,'2.2 Diesel','Automat','SUV'],['sportage-2023','Kia','Sportage','2023',70,49,'2.0 Diesel','Automat','SUV'],['santa-fe-2020','Hyundai','Santa Fe','2020 · 7 vende',70,49,'2.2 Diesel','Automat','SUV'],['santa-fe-2015','Hyundai','Santa Fe','2015 · E bardhë',60,42,'2.2 Diesel','Automat','SUV'],['carnival','Kia','Carnival','2017 · 9 vende',75,52.5,'2.0 Diesel','',''],['evoque','Land Rover','Range Rover Evoque','E bardhë',65,45.5,'2.2 Diesel','Automat','SUV'],['evoque-grey','Land Rover','Range Rover Evoque','Gri',65,45.5,'2.2 Diesel','Automat','SUV'],['tiguan','Volkswagen','Tiguan','',55,38.5,'2.0 Diesel','Automat','SUV'],['clio','Renault','Clio','2015',38,26.6,'1.5 Diesel','Manual',''],['fiesta','Ford','Fiesta','',38,26.6,'1.5 Diesel','Manual',''],['c-elysee','Citroën','C-Elysée','2017',40,28,'1.6 Diesel','Manual',''],['golf-7-manual','Volkswagen','Golf 7 Variant','1.2 Benzinë',40,28,'1.2 Benzinë','Manual','Bagazh i madh · Tavan panoramik'],['peugeot-2019','Peugeot','208','2019',38,26.6,'1.6 Diesel','Manual','Multimedia · Bluetooth · Navigim'],['fabia-petrol','Škoda','Fabia','1.2 Benzinë',36,25.2,'1.2 Benzinë','Manual',''],['fabia-diesel','Škoda','Fabia','1.6 Diesel',36,25.2,'1.6 Diesel','',''],['sportage-2018','Kia','Sportage','2018 · E bardhë',55,38.5,'2.0 Diesel','Automat','SUV · Sunroof · Android Auto · Apple CarPlay']
].map(x=>({id:x[0],brand:x[1],model:x[2],meta:x[3],price:x[4],sale:x[5],engine:x[6],trans:x[7],tag:x[8],image:imgs[x[1]]}));
cars.find(c=>c.id==='chery-tiggo-8').image='assets/cars/chery-tiggo-8/main.png';
cars.find(c=>c.id==='chery-fx').image='assets/cars/chery-fx/main.jpeg';
cars.find(c=>c.id==='palisade').image='assets/cars/hyundai-palisade/main.jpeg';
cars.find(c=>c.id==='sportage-2023').image='assets/cars/kia-sportage-2023/main.png';
cars.find(c=>c.id==='santa-fe-2020').image='assets/cars/hyundai-santa-fe-2020/main.png';
cars.find(c=>c.id==='santa-fe-2015').image='assets/cars/hyundai-santa-fe-2015/main.png';
cars.find(c=>c.id==='carnival').image='assets/cars/kia-carnival/main.jpeg';
cars.find(c=>c.id==='evoque').image='assets/cars/range-rover-evoque/main.png';
cars.find(c=>c.id==='evoque-grey').image='assets/cars/range-rover-evoque-grey/main.png';
cars.find(c=>c.id==='tiguan').image='assets/cars/volkswagen-tiguan/main.png';
cars.find(c=>c.id==='clio').image='assets/cars/renault-clio/main.jpeg';
cars.find(c=>c.id==='fiesta').image='assets/cars/ford-fiesta/main.png';
cars.find(c=>c.id==='c-elysee').image='assets/cars/citroen-c-elysee/main.png';
cars.find(c=>c.id==='golf-7-manual').image='assets/cars/volkswagen-golf-7-variant/main.jpeg';
cars.find(c=>c.id==='peugeot-2019').image='assets/cars/peugeot-208/main.png';
cars.find(c=>c.id==='fabia-diesel').trans='Manual';
cars.find(c=>c.id==='fabia-diesel').image='assets/cars/skoda-fabia-diesel/main.jpeg';
cars.find(c=>c.id==='sportage-2018').image='assets/cars/kia-sportage-2018/main.png';
cars.find(c=>c.id==='audi-a4').image='assets/cars/audi-a4/main.png';
cars.find(c=>c.id==='audi-a5').image='assets/cars/audi-a5/main.png';
cars.find(c=>c.id==='audi-a7').image='assets/cars/audi-a7/main.png';
cars.find(c=>c.id==='bmw-1-1').image='assets/cars/bmw-series-1/main.png';
cars.find(c=>c.id==='bmw-1-2').image='assets/cars/bmw-series-1-white/main.png';
cars.find(c=>c.id==='cla').image='assets/cars/mercedes-cla/main.png';
cars.find(c=>c.id==='c-class').image='assets/cars/mercedes-c-class/main.png';
cars.find(c=>c.id==='focus').image='assets/cars/ford-focus/main.png';
cars.find(c=>c.id==='audi-a3').image='assets/cars/audi-a3/main.jpg';
cars.find(c=>c.id==='bmw-3').image='assets/cars/bmw-series-3/main.jpg';
cars.find(c=>c.id==='i30').image='assets/cars/hyundai-i30/main.jpg';
cars.find(c=>c.id==='mg3').image='assets/cars/mg3/main.jpg';
cars.find(c=>c.id==='fabia-petrol').image='assets/cars/skoda-fabia-petrol/main.jpg';
cars.find(c=>c.id==='bayon').image='assets/cars/hyundai-bayon/main.jpg';
cars.find(c=>c.id==='stonic-1').image='assets/cars/kia-stonic/main.jpg';
cars.find(c=>c.id==='stonic-2').image='assets/cars/kia-stonic/main.jpg';
cars.find(c=>c.id==='stonic-3').image='assets/cars/kia-stonic/main.jpg';
cars.find(c=>c.id==='kona').image='assets/cars/hyundai-kona/main.jpg';
cars.find(c=>c.id==='golf-6').image='assets/cars/volkswagen-golf-6-automatic/main.png';
cars.find(c=>c.id==='golf-7').image='assets/cars/volkswagen-golf-7-automatic/main.jpg';

const carGalleries={
  'audi-a5':['assets/cars/audi-a5/main.png','assets/cars/audi-a5/02.png','assets/cars/audi-a5/03.png'],
  'audi-a7':['assets/cars/audi-a7/main.png','assets/cars/audi-a7/02.png'],
  'bmw-1-1':['assets/cars/bmw-series-1/main.png','assets/cars/bmw-series-1/02.png'],
  'bmw-1-2':['assets/cars/bmw-series-1-white/main.png','assets/cars/bmw-series-1-white/02.png','assets/cars/bmw-series-1-white/03.png'],
  'cla':['assets/cars/mercedes-cla/main.png','assets/cars/mercedes-cla/02.png','assets/cars/mercedes-cla/03.png','assets/cars/mercedes-cla/04.png'],
  'c-class':['assets/cars/mercedes-c-class/main.png','assets/cars/mercedes-c-class/02.png'],
  'focus':['assets/cars/ford-focus/main.png','assets/cars/ford-focus/02.png','assets/cars/ford-focus/03.png','assets/cars/ford-focus/04.png']
};
Object.assign(carGalleries,{
  'audi-a3':['assets/cars/audi-a3/main.jpg','assets/cars/audi-a3/rear.jpg','assets/cars/audi-a3/front.jpg','assets/cars/audi-a3/interior.jpg'],
  'audi-a4':['assets/cars/audi-a4/main.png','assets/cars/audi-a4/angle.png','assets/cars/audi-a4/rear.png','assets/cars/audi-a4/interior.png'],
  'bmw-3':['assets/cars/bmw-series-3/main.jpg','assets/cars/bmw-series-3/rear.jpg','assets/cars/bmw-series-3/rear-seats.jpg','assets/cars/bmw-series-3/front-cabin.jpg'],
  'i30':['assets/cars/hyundai-i30/main.jpg','assets/cars/hyundai-i30/rear.jpg','assets/cars/hyundai-i30/front.jpg','assets/cars/hyundai-i30/rear-straight.jpg','assets/cars/hyundai-i30/panoramic-roof.jpg','assets/cars/hyundai-i30/interior.jpg'],
  'mg3':['assets/cars/mg3/main.jpg','assets/cars/mg3/rear.jpg','assets/cars/mg3/carplay.jpg','assets/cars/mg3/front-seats.jpg','assets/cars/mg3/luggage.jpg','assets/cars/mg3/interior.jpg'],
  'chery-tiggo-8':['assets/cars/chery-tiggo-8/main.png','assets/cars/chery-tiggo-8/rear.png','assets/cars/chery-tiggo-8/front.jpeg','assets/cars/chery-tiggo-8/interior-camera.jpeg','assets/cars/chery-tiggo-8/interior-cockpit.jpeg','assets/cars/chery-tiggo-8/interior-driving.jpeg','assets/cars/chery-tiggo-8/interior-roof.jpeg','assets/cars/chery-tiggo-8/interior-wide.jpeg'],
  'chery-fx':['assets/cars/chery-fx/main.jpeg','assets/cars/chery-fx/interior-front.jpeg','assets/cars/chery-fx/interior-rear.jpeg','assets/cars/chery-fx/interior-wide.jpeg'],
  'palisade':['assets/cars/hyundai-palisade/main.jpeg','assets/cars/hyundai-palisade/rear.png','assets/cars/hyundai-palisade/front.jpeg','assets/cars/hyundai-palisade/grille.jpeg','assets/cars/hyundai-palisade/interior.jpeg','assets/cars/hyundai-palisade/digital-cluster.jpeg','assets/cars/hyundai-palisade/taillight.jpeg'],
  'sportage-2023':['assets/cars/kia-sportage-2023/main.png','assets/cars/kia-sportage-2023/rear.png','assets/cars/kia-sportage-2023/side.jpeg','assets/cars/kia-sportage-2023/dashboard.jpeg','assets/cars/kia-sportage-2023/driver-view.jpeg','assets/cars/kia-sportage-2023/interior-front.jpeg','assets/cars/kia-sportage-2023/interior-wide.jpeg','assets/cars/kia-sportage-2023/rear-seats.jpeg'],
  'santa-fe-2020':['assets/cars/hyundai-santa-fe-2020/main.png','assets/cars/hyundai-santa-fe-2020/rear.png','assets/cars/hyundai-santa-fe-2020/side.jpeg','assets/cars/hyundai-santa-fe-2020/interior.jpeg'],
  'santa-fe-2015':['assets/cars/hyundai-santa-fe-2015/main.png','assets/cars/hyundai-santa-fe-2015/rear.png','assets/cars/hyundai-santa-fe-2015/dashboard-panorama.jpeg','assets/cars/hyundai-santa-fe-2015/rear-cabin.jpeg','assets/cars/hyundai-santa-fe-2015/rear-seats.jpeg','assets/cars/hyundai-santa-fe-2015/third-row.jpeg'],
  'carnival':['assets/cars/kia-carnival/main.jpeg','assets/cars/kia-carnival/front.png','assets/cars/kia-carnival/rear.png','assets/cars/kia-carnival/driver-cabin.jpeg','assets/cars/kia-carnival/passenger-seating.jpeg','assets/cars/kia-carnival/sliding-door-cabin.jpeg'],
  'evoque':['assets/cars/range-rover-evoque/main.png','assets/cars/range-rover-evoque/rear.png','assets/cars/range-rover-evoque/side.jpeg','assets/cars/range-rover-evoque/automatic-console.jpeg','assets/cars/range-rover-evoque/front-seats.jpeg','assets/cars/range-rover-evoque/meridian-audio.jpeg','assets/cars/range-rover-evoque/panoramic-cabin.jpeg','assets/cars/range-rover-evoque/rear-seats.jpeg'],
  'evoque-grey':['assets/cars/range-rover-evoque-grey/main.png','assets/cars/range-rover-evoque-grey/rear.png','assets/cars/range-rover-evoque-grey/front-cabin.jpeg','assets/cars/range-rover-evoque-grey/rear-seats-panorama.jpeg'],
  'tiguan':['assets/cars/volkswagen-tiguan/main.png','assets/cars/volkswagen-tiguan/rear-luggage.png','assets/cars/volkswagen-tiguan/front-cabin.jpeg','assets/cars/volkswagen-tiguan/rear-seats-panorama.jpeg'],
  'clio':['assets/cars/renault-clio/main.jpeg','assets/cars/renault-clio/front.png','assets/cars/renault-clio/rear.png','assets/cars/renault-clio/manual-dashboard.jpeg'],
  'fiesta':['assets/cars/ford-fiesta/main.png','assets/cars/ford-fiesta/rear.png','assets/cars/ford-fiesta/manual-dashboard.jpeg'],
  'c-elysee':['assets/cars/citroen-c-elysee/main.png','assets/cars/citroen-c-elysee/front.png'],
  'golf-7-manual':['assets/cars/volkswagen-golf-7-variant/main.jpeg','assets/cars/volkswagen-golf-7-variant/rear.jpeg','assets/cars/volkswagen-golf-7-variant/dashboard.jpeg','assets/cars/volkswagen-golf-7-variant/interior.jpeg'],
  'peugeot-2019':['assets/cars/peugeot-208/main.png','assets/cars/peugeot-208/side.png','assets/cars/peugeot-208/interior.jpeg'],
  'fabia-petrol':['assets/cars/skoda-fabia-petrol/main.jpg','assets/cars/skoda-fabia-petrol/rear.jpg'],
  'fabia-diesel':['assets/cars/skoda-fabia-diesel/main.jpeg','assets/cars/skoda-fabia-diesel/rear.jpeg','assets/cars/skoda-fabia-diesel/dashboard.jpeg','assets/cars/skoda-fabia-diesel/interior.jpeg'],
  'bayon':['assets/cars/hyundai-bayon/main.jpg','assets/cars/hyundai-bayon/rear.jpg','assets/cars/hyundai-bayon/front.jpg','assets/cars/hyundai-bayon/front-cabin.jpg','assets/cars/hyundai-bayon/rear-seats.jpg'],
  'stonic-1':['assets/cars/kia-stonic/main.jpg','assets/cars/kia-stonic/side.jpg','assets/cars/kia-stonic/cabin.jpg'],
  'stonic-2':['assets/cars/kia-stonic/main.jpg','assets/cars/kia-stonic/side.jpg','assets/cars/kia-stonic/cabin.jpg'],
  'stonic-3':['assets/cars/kia-stonic/main.jpg','assets/cars/kia-stonic/side.jpg','assets/cars/kia-stonic/cabin.jpg'],
  'kona':['assets/cars/hyundai-kona/main.jpg','assets/cars/hyundai-kona/rear-side.jpg','assets/cars/hyundai-kona/luggage.jpg','assets/cars/hyundai-kona/dashboard.jpg'],
  'golf-6':['assets/cars/volkswagen-golf-6-automatic/main.png','assets/cars/volkswagen-golf-6-automatic/front.png','assets/cars/volkswagen-golf-6-automatic/interior.jpg'],
  'golf-7':['assets/cars/volkswagen-golf-7-automatic/main.jpg','assets/cars/volkswagen-golf-7-automatic/front.jpg','assets/cars/volkswagen-golf-7-automatic/rear.jpg','assets/cars/volkswagen-golf-7-automatic/interior.jpg'],
  'sportage-2018':['assets/cars/kia-sportage-2018/main.png','assets/cars/kia-sportage-2018/rear.png']
});
let blocked={}; const money=n=>`€${Number.isInteger(n)?n:n.toFixed(2)}`; const iso=d=>d.toISOString().slice(0,10); const today=iso(new Date());
document.querySelectorAll('input[type=date]').forEach(i=>{i.min=today;i.max=C.seasonEnd});
async function loadBlocked(){if(S){const {data}=await S.from('blocked_dates').select('*');(data||[]).forEach(b=>(blocked[b.vehicle_id]??=[]).push([b.start_date,b.end_date]));}else blocked=JSON.parse(localStorage.getItem('kambos_blocked')||'{}');render();}
const unavailable=(id,start,end)=>{if(!start||!end)return false;const s=new Date(start+'T12:00'),e=new Date(end+'T12:00');return (blocked[id]||[]).some(([a,b])=>s<=new Date(b+'T12:00')&&e>=new Date(a+'T12:00'));};
function localText(value){if(currentLang==='en')return value.replaceAll('Njësia','Unit').replaceAll('vende','seats').replaceAll('E bardhë','White').replaceAll('Gri','Grey').replaceAll('Benzinë','Petrol').replaceAll('Automat','Automatic').replaceAll('Bagazh i madh','Large luggage space').replaceAll('Tavan panoramik','Panoramic roof').replaceAll('Navigim','Navigation');return value}
function render(filter='all'){const s=globalStart.value,e=globalEnd.value,t=T();let list=cars.filter(c=>filter==='all'||c.brand===filter||c.tag.includes(filter));if(s&&e)list=list.filter(c=>!unavailable(c.id,s,e));fleetStatus.textContent=`${list.length} ${t.available}${s&&e?' '+t.chosen:''}.`;fleetGrid.innerHTML=list.map(c=>`<article class="car-card"><button class="car-open" data-id="${c.id}"><div class="car-image"><img src="${c.image}" alt="${c.brand} ${c.model}" loading="lazy"></div><div class="car-body"><small>${localText(c.meta||c.brand)}</small><h3>${c.brand} ${c.model}</h3><div class="specs"><span>${localText(c.trans||c.engine||t.doors)}</span><span>${localText(c.engine&&c.trans?c.engine:t.doors)}</span></div><span class="availability-link">${currentLang==='en'?'Check dates & price':'Kontrollo datat dhe çmimin'} →</span></div></button></article>`).join('');document.querySelectorAll('.car-open').forEach(b=>b.onclick=()=>openCar(b.dataset.id));}
function priceFor(start,end,car){const a=new Date(start+'T12:00'),b=new Date(end+'T12:00');let days=Math.max(1,Math.round((b-a)/864e5)),normal=0,sale=0,winter=0,total=0;for(let i=0;i<days;i++){const d=new Date(a);d.setDate(d.getDate()+i);if(d>=new Date('2027-06-01T12:00')){sale++;total+=car.price*.9}else if(d>=new Date('2027-04-01T12:00')){sale++;total+=car.price*.7}else if(d>=new Date('2027-03-31T12:00')){normal++;total+=car.price}else if(d>=new Date('2027-01-16T12:00')){sale++;total+=car.price*.65}else if(d>=new Date('2026-12-15T12:00')){winter++;total+=car.sale*1.2}else if(d>=new Date('2026-09-15T12:00')){sale++;total+=car.sale}else{normal++;total+=car.price}}return{days,normal,sale,winter,total};}
function openCar(id){const c=cars.find(x=>x.id===id),s=globalStart.value,e=globalEnd.value,gallery=carGalleries[id]||[c.image],t=T();modalContent.innerHTML=`<div class="modal-hero"><div class="modal-gallery"><img class="modal-main-image" src="${gallery[0]}" alt="${c.brand} ${c.model}">${gallery.length>1?`<div class="modal-thumbs">${gallery.map((src,index)=>`<button class="modal-thumb${index===0?' active':''}" type="button" data-src="${src}" aria-label="${t.photo} ${index+1}"><img src="${src}" alt=""></button>`).join('')}</div>`:''}</div><div><span>${localText(c.meta||c.brand)}</span><h2>${c.brand} ${c.model}</h2><p>${[c.engine,c.trans,c.tag,t.doors].filter(Boolean).map(localText).join(' · ')}</p></div></div><form id="reserveForm"><div class="form-grid"><label>${t.fullName}<input name="name" required></label><label>${t.phone}<input name="phone" type="tel" required></label><label>${t.pickupTime}<input name="startTime" type="time" required></label><label>${t.returnTime}<input name="endTime" type="time" required></label></div><input name="start" type="hidden" value="${s}"><input name="end" type="hidden" value="${e}"><div class="calendar-wrap"><div class="calendar-head"><button type="button" class="cal-nav" id="calPrev">‹</button><div><b id="monthLabel"></b><small id="selectionLabel">${t.selectDates}</small></div><button type="button" class="cal-nav" id="calNext">›</button></div><div class="calendar-legend"><span><i class="legend-available"></i>${t.availableDay}</span><span><i class="legend-blocked"></i>${t.reserved}</span><span><i class="legend-selected"></i>${t.selected}</span></div><div class="calendar-grid" id="calendarGrid"></div></div><label class="check"><input name="seat" type="checkbox"> ${t.childSeat} <b>€4${t.perDay}</b></label><label class="check"><input name="insurance" type="checkbox"> ${t.insurance} <b>€15${t.perDay}</b></label><label class="check"><input name="crossBorder" type="checkbox"> ${t.crossBorder} <b>€50 (${currentLang==='sq'?'vetëm një herë':'one-time fee'})</b></label><label class="check"><input name="addDriver" type="checkbox"> ${t.addDriver} <b>€3${t.perDay}</b></label><label>${t.note}<textarea name="note" rows="3"></textarea></label><div class="availability" id="availability">${t.seePrice}</div><button class="btn full" type="submit">${t.send}</button><small>${t.confirmation}</small></form>`;bookingModal.classList.add('show');bookingModal.ariaHidden='false';modalContent.querySelectorAll('.modal-thumb').forEach(btn=>btn.onclick=()=>{modalContent.querySelector('.modal-main-image').src=btn.dataset.src;modalContent.querySelectorAll('.modal-thumb').forEach(x=>x.classList.remove('active'));btn.classList.add('active')});const f=document.querySelector('#reserveForm');f.oninput=()=>quote(f,c);f.onsubmit=x=>send(x,f,c);initCalendar(f,c);quote(f,c);}
function initCalendar(f,c){const months=['Janar','Shkurt','Mars','Prill','Maj','Qershor','Korrik','Gusht','Shtator','Tetor','Nëntor','Dhjetor'],days=['Hë','Ma','Më','En','Pr','Sh','Di'];let view=f.start.value?new Date(f.start.value+'T12:00'):new Date();view=new Date(view.getFullYear(),view.getMonth(),1,12);const min=new Date(today+'T12:00'),max=new Date(C.seasonEnd+'T12:00');function rangeHasBlock(a,b){for(let d=new Date(a);d<=b;d.setDate(d.getDate()+1))if(unavailable(c.id,iso(d),iso(d)))return true;return false}function draw(){monthLabel.textContent=`${months[view.getMonth()]} ${view.getFullYear()}`;const first=(new Date(view.getFullYear(),view.getMonth(),1).getDay()+6)%7,last=new Date(view.getFullYear(),view.getMonth()+1,0).getDate();let html=days.map(d=>`<span class="cal-dayname">${d}</span>`).join('')+Array(first).fill('<span></span>').join('');for(let n=1;n<=last;n++){const d=new Date(view.getFullYear(),view.getMonth(),n,12),key=iso(d),isBlocked=unavailable(c.id,key,key),disabled=d<min||d>max||isBlocked,selected=key===f.start.value||key===f.end.value,inRange=f.start.value&&f.end.value&&key>f.start.value&&key<f.end.value;html+=`<button type="button" class="cal-day${isBlocked?' blocked':''}${selected?' selected':''}${inRange?' in-range':''}" data-date="${key}" ${disabled?'disabled':''}>${n}</button>`}calendarGrid.innerHTML=html;selectionLabel.textContent=f.start.value?(f.end.value?`${f.start.value} → ${f.end.value}`:`Marrja: ${f.start.value} · zgjidh kthimin`):'Zgjidh datën e marrjes dhe kthimit';calendarGrid.querySelectorAll('.cal-day:not(:disabled)').forEach(b=>b.onclick=()=>pick(b.dataset.date));calPrev.disabled=new Date(view.getFullYear(),view.getMonth()+1,0)<min;calNext.disabled=new Date(view.getFullYear(),view.getMonth()+1,1)>max}function pick(key){if(!f.start.value||f.end.value){f.start.value=key;f.end.value=''}else if(key<f.start.value){f.start.value=key;f.end.value=''}else{const a=new Date(f.start.value+'T12:00'),b=new Date(key+'T12:00');if(rangeHasBlock(a,b)){availability.className='availability bad';availability.textContent='Intervali përmban data të rezervuara. Zgjidh një interval tjetër.';return}f.end.value=key}draw();quote(f,c)}calPrev.onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()-1,1,12);draw()};calNext.onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1,12);draw()};draw()}
function quote(f,c){const s=f.start.value,e=f.end.value,box=document.querySelector('#availability'),t=T();if(!s||!e)return;if(e<s){box.className='availability bad';box.textContent=t.badOrder;return}if(unavailable(c.id,s,e)){box.className='availability bad';box.textContent=t.blocked;return}const p=priceFor(s,e,c),seat=f.seat.checked?p.days*4:0,insurance=f.insurance.checked?p.days*15:0,crossBorder=f.crossBorder.checked?50:0,addDriver=f.addDriver.checked?p.days*3:0,total=p.total+seat+insurance+crossBorder+addDriver;box.className='availability';box.innerHTML=`<span>${p.days} ${t.days}</span><span>${t.car}: ${money(p.total)}</span>${seat?`<span>${t.childSeat}: ${money(seat)} (€4${t.perDay})</span>`:''}${insurance?`<span>${t.insurance}: ${money(insurance)} (€15${t.perDay})</span>`:''}${crossBorder?`<span>${t.crossBorder}: €50 (${currentLang==='sq'?'një herë':'one time'})</span>`:''}${addDriver?`<span>${t.addDriver}: ${money(addDriver)} (€3${t.perDay})</span>`:''}<b>${t.total}: ${money(total)}</b>`;}
function send(ev,f,c){ev.preventDefault();if(unavailable(c.id,f.start.value,f.end.value))return quote(f,c);const p=priceFor(f.start.value,f.end.value,c),seat=f.seat.checked?p.days*4:0,insurance=f.insurance.checked?p.days*15:0,crossBorder=f.crossBorder.checked?50:0,addDriver=f.addDriver.checked?p.days*3:0,total=p.total+seat+insurance+crossBorder+addDriver;const sq=currentLang==='sq';const msg=sq?`Përshëndetje KamboS Rental Car!\n\nDëshiroj të kërkoj një rezervim.\n\nMakina: ${c.brand} ${c.model} ${c.meta}\nEmri: ${f.name.value}\nTelefoni: ${f.phone.value}\nData e marrjes: ${f.start.value}\nOra e marrjes: ${f.startTime.value}\nData e kthimit: ${f.end.value}\nOra e kthimit: ${f.endTime.value}\nNumri i ditëve: ${p.days}\nÇmimi për makinën: ${money(p.total)}\nKarrige për fëmijë: ${f.seat.checked?`Po, ${money(seat)} (€4/ditë)`:'Jo'}\nSiguracion i plotë: ${f.insurance.checked?`Po, ${money(insurance)} (€15/ditë)`:'Jo'}\nCross border: ${f.crossBorder.checked?'Po, €50 (një herë)':'Jo'}\nShofer shtesë: ${f.addDriver.checked?`Po, ${money(addDriver)} (€3/ditë)`:'Jo'}\nTotali: ${money(total)}\nShënim: ${f.note.value||'-'}\n\nJu lutem më konfirmoni disponueshmërinë. Faleminderit!`:`Hello KamboS Rental Car!\n\nI would like to request a reservation.\n\nCar: ${c.brand} ${c.model} ${c.meta}\nName: ${f.name.value}\nPhone: ${f.phone.value}\nPick-up date: ${f.start.value}\nPick-up time: ${f.startTime.value}\nReturn date: ${f.end.value}\nReturn time: ${f.endTime.value}\nNumber of days: ${p.days}\nCar price: ${money(p.total)}\nChild seat: ${f.seat.checked?`Yes, ${money(seat)} (€4/day)`:'No'}\nFull insurance: ${f.insurance.checked?`Yes, ${money(insurance)} (€15/day)`:'No'}\nCross border: ${f.crossBorder.checked?'Yes, €50 (one time)':'No'}\nAdditional driver: ${f.addDriver.checked?`Yes, ${money(addDriver)} (€3/day)`:'No'}\nTotal: ${money(total)}\nNote: ${f.note.value||'-'}\n\nPlease confirm availability. Thank you!`;window.open(`https://wa.me/${C.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank');}
function initCalendar(f,c){
  const monthNames=currentLang==='en'?['January','February','March','April','May','June','July','August','September','October','November','December']:['Janar','Shkurt','Mars','Prill','Maj','Qershor','Korrik','Gusht','Shtator','Tetor','Nëntor','Dhjetor'];
  const dayNames=currentLang==='en'?['Mo','Tu','We','Th','Fr','Sa','Su']:['Hë','Ma','Më','En','Pr','Sh','Di'];
  let view=f.start.value?new Date(f.start.value+'T12:00'):new Date(); view=new Date(view.getFullYear(),view.getMonth(),1,12);
  const min=new Date(today+'T12:00'),max=new Date(C.seasonEnd+'T12:00');
  const hasBlocked=(a,b)=>{for(let d=new Date(a);d<=b;d.setDate(d.getDate()+1))if(unavailable(c.id,iso(d),iso(d)))return true;return false};
  function draw(){
    monthLabel.textContent=`${monthNames[view.getMonth()]} ${view.getFullYear()}`;
    const first=(new Date(view.getFullYear(),view.getMonth(),1).getDay()+6)%7,last=new Date(view.getFullYear(),view.getMonth()+1,0).getDate();
    let html=dayNames.map(d=>`<span class="cal-dayname">${d}</span>`).join('')+Array(first).fill('<span></span>').join('');
    for(let n=1;n<=last;n++){const d=new Date(view.getFullYear(),view.getMonth(),n,12),key=iso(d),red=unavailable(c.id,key,key),disabled=d<min||d>max||red,selected=key===f.start.value||key===f.end.value,inRange=f.start.value&&f.end.value&&key>f.start.value&&key<f.end.value;html+=`<button type="button" class="cal-day${red?' blocked':''}${selected?' selected':''}${inRange?' in-range':''}" data-date="${key}" ${disabled?'disabled':''}>${n}</button>`}
    calendarGrid.innerHTML=html;
    selectionLabel.textContent=f.start.value?(f.end.value?`${f.start.value} → ${f.end.value}`:`${currentLang==='en'?'Pick-up':'Marrja'}: ${f.start.value} · ${currentLang==='en'?'choose return':'zgjidh kthimin'}`):T().selectDates;
    calendarGrid.querySelectorAll('.cal-day:not(:disabled)').forEach(b=>b.onclick=()=>pick(b.dataset.date));
    calPrev.disabled=new Date(view.getFullYear(),view.getMonth()+1,0)<min; calNext.disabled=new Date(view.getFullYear(),view.getMonth()+1,1)>max;
  }
  function pick(key){if(!f.start.value||f.end.value){f.start.value=key;f.end.value=''}else if(key<f.start.value){f.start.value=key;f.end.value=''}else{const a=new Date(f.start.value+'T12:00'),b=new Date(key+'T12:00');if(hasBlocked(a,b)){availability.className='availability bad';availability.textContent=T().blockedRange;return}f.end.value=key}draw();quote(f,c)}
  calPrev.onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()-1,1,12);draw()}; calNext.onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1,12);draw()}; draw();
}
const reviews={sq:[['Ardit K.','Makina ishte e pastër, komode dhe gati në kohë. Rezervimi ishte shumë i thjeshtë.'],['Elona M.','Komunikim i shpejtë dhe shërbim shumë korrekt. Patjetër do të rezervoj përsëri.'],['Besnik H.','Çmimi ishte transparent dhe makina ishte në gjendje shumë të mirë.'],['Sara D.','Rezervimi në WhatsApp ishte i lehtë dhe përgjigjja erdhi shumë shpejt.'],['Erion L.','Shërbim profesional, staf i sjellshëm dhe makinë shumë e pastër.']],en:[['Ardit K.','The car was clean, comfortable and ready on time. Booking was very easy.'],['Elona M.','Fast communication and excellent service. I will definitely book again.'],['Besnik H.','The price was transparent and the car was in very good condition.'],['Sara D.','Booking through WhatsApp was easy and the reply came very quickly.'],['Erion L.','Professional service, friendly staff and a very clean car.']]};function renderReviews(){reviewTrack.innerHTML=[...reviews[currentLang],...reviews[currentLang]].map(r=>`<article><div class="stars">★★★★★</div><p>“${r[1]}”</p><b>${r[0]}</b></article>`).join('')}
findCars.onclick=()=>render(document.querySelector('.filter.active').dataset.filter);document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');render(b.dataset.filter)});document.querySelector('.close').onclick=()=>bookingModal.classList.remove('show');bookingModal.onclick=e=>{if(e.target===bookingModal)bookingModal.classList.remove('show')};document.querySelector('.menu').onclick=()=>document.querySelector('nav').classList.toggle('open');document.querySelector('.lang').onclick=()=>{currentLang=currentLang==='sq'?'en':'sq';localStorage.setItem('kambos_lang_v13',currentLang);bookingModal.classList.remove('show');translateStatic();render(document.querySelector('.filter.active').dataset.filter);renderReviews()};translateStatic();renderReviews();render();loadBlocked();
